### ISSUE TITLE
Crashing Rhino on Load

### ISSUE THREAD

**Issue by EricM81** [goswinr/Fesh.Rhino#2]
This is a hard crash that exits Rhino at the first frame of the Fesh editor being rendered on screen.  No error message is produced, but it does offer to send a crash report to McNeel, which I did (once).  Here is a log written to the desktop:

[Fesh.Rhino-Fittings-UnhandledException-2024-10-07_19-18-51-017.txt](https://github.com/user-attachments/files/17295753/Fesh.Rhino-Fittings-UnhandledException-2024-10-07_19-18-51-017.txt)

Other crashes had the same basic information.

The standalone editor works fine.

**Comment by goswinr** [comment]
`System.MissingMethodException: Method not found: 'Boolean Microsoft.FSharp.Collections.FSharpList`1.Equals(Microsoft.FSharp.Collections.FSharpList`1<!0>, System.Collections.IEqualityComparer)'.`
This probably means that an older Version of `Fsharp.Core` is already loaded. I might have top add a check about that add plugin start up.

**Comment by goswinr** [comment]
Can you try adding a [binding redirect](https://learn.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions?redirectedfrom=MSDN#specify-assembly-binding-in-configuration-files) between the `<runtime>` and `</runtime>` tag in `Rhino.exe.config`  ( in the same folder as Rhino.exe) ?
Use this: 
```xml
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
    <dependentAssembly>
       <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
       <bindingRedirect oldVersion="0.0.0.0-8.0.400" newVersion="8.0.400" />
    </dependentAssembly>
</assemblyBinding>
```

**Comment by goswinr** [comment]
also see https://discourse.mcneel.com/t/is-it-ok-to-add-binding-redirects-to-rhino-exe-config-file/192936

**Comment by EricM81** [comment]
That's not working.  My plugin, which I set back to 8.0.300, loads first.  Since 8.0.400 isn't loaded, it starts searching for `FSharp.Core.dll`, and the path to your plugin isn't in the search tree.  So it loads my 8.0.300, which crashes Fesh.

Here is my full rhino.exe.config after adding the redirect:
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <appSettings>
        <add key="EnableWindowsFormsHighDpiAutoResizing" value="true" />
    </appSettings>
    <runtime>
        <AppContextSwitchOverrides value="Switch.MS.Internal.DoNotApplyLayoutRoundingToMarginsAndBorderThickness=false;Switch.System.Windows.DoNotScaleForDpiChanges=false" />
		<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
			<dependentAssembly>
			   <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
			   <bindingRedirect oldVersion="0.0.0.0-8.0.400" newVersion="8.0.400" />
			</dependentAssembly>
		</assemblyBinding>
	</runtime>
</configuration>
```

**Comment by goswinr** [comment]
I think catching the async exception is actually good enough, so that the plugin can still load fully ( but not allow fsi evaluation) . On restarting rhino it should then have the correct dll. I will try that..

**Comment by goswinr** [comment]
Eric, can you update to 0.13? https://github.com/goswinr/Fesh.Rhino/releases  the should be fixed after a restart.

**Comment by goswinr** [comment]
@EricM81 I think this is solved, if not please reopen
