### ISSUE TITLE
Could not do something; another thread owns xxx

### ISSUE THREAD

**Issue by EricM81** [goswinr/Fesh.Rhino#3]
I don't have the exact error message because the UI is frozen.  I was trying to change the view state on a bunch of layers.  The layers follow this format:
```
<function>::<partname>::Ctrl
<function>::<partname>::Ctrl::Junk
<function>::<partname>::Crvs
<function>::<partname>::Crvs::Junk
i.e.
Cutter::Prong::Ctrl::Junk
```
This is the script:
```
#r "C:/Program Files/Rhino 8/System/RhinoCommon.dll" 
#r "nuget:Rhino.Scripting.Fsharp, 0.8.1"  

open System
open Rhino.DocObjects
open Rhino.Scripting
open Rhino.Scripting.Fsharp //recommended for F# 
open FsEx // part of Rhino.Scripting

type rs = RhinoScriptSyntax

let nameP (s1: string)  (s2: string) : bool =  
    System.String.Compare(s1, s2, System.StringComparison.InvariantCultureIgnoreCase) = 0
    
let printLayer (layer: Layer): string =  
    layer.FullPath.Replace("::", "->")
    
let turnOffLayer (layer: Layer) = 
    let targetName = "crvs"
    let viewP = true
    
    if (nameP layer.Name targetName) then
        let a = new Layer()
        a.CopyAttributesFrom(layer)
        a.IsExpanded <- true
        a.IsVisible <- viewP
        let resP = rs.Doc.Layers.Modify(a, layer.Index, false)
        if resP = true then  
            Rhino.RhinoApp.WriteLine($"Updated layer {printLayer layer}") 
            
        else
            Rhino.RhinoApp.WriteLine($"ERROR: Could not updated layer {printLayer layer}")
            
        resP
    else true
    
rs.Doc.Layers |> Seq.forall turnOffLayer
```
The script worked for the first two executions ("Junk" off, "Control" off), but the third run ("Crvs" on) gave a threading error message saying something along the lines of the calling thread couldn't do something because another thread owned the resource.  I tried to switch to Rhino to see if there was a message there, but the UI was frozen and I couldn't get Fesh back.

**Comment by EricM81** [comment]
I kept playing with it, and it looks like a Rhino issue is the root cause:

https://discourse.mcneel.com/t/how-to-update-layer-parent/191309/7?u=ericm

I don't know if there's anything you could do to prevent the UI from locking up.

**Comment by goswinr** [comment]
Do you have a  *.3dm file to test this on ?
Here you can switch to synchronous evaluation: 
![image](https://github.com/user-attachments/assets/c7c3b096-99ea-4783-9942-a00a1a3e23e6)

**Comment by EricM81** [comment]
I sent you a link to the 3dm on Discourse.  

Why does it default to async execution?

**Comment by goswinr** [comment]
I will switch the default to Sync.
 I use Fesh.Rhino mostly with https://github.com/goswinr/Rhino.Scripting. It has a context switch for all functions that need to run in sync built in.

**Comment by goswinr** [comment]
the Modify method will trigger a UI message, so it needs to run Sync: 
![image](https://github.com/user-attachments/assets/bae96996-6e1a-4a72-a136-07aab9a861c6)

**Comment by goswinr** [comment]
Just set the last arg in` Modify` to` true`,  then it works async. You are anyway logging the result. You can log the result in color with some functions in Rhino.Scripting: 
![image](https://github.com/user-attachments/assets/51f8f4f6-d9f3-4fcc-9e4c-f8bc7a0dda9b)

**Comment by EricM81** [comment]
It looks like either option makes it work properly.
